# Generated by Django 6.0.5 on 2026-07-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('study', 'Study'), ('other', 'Other')], default='personal', max_length=20),
        ),
    ]
